#!/usr/bin/env bash

set -e
echo "Building client ..."
npm run build > /dev/null
echo "Client Built."

echo "Removing extra files ..."
rm -rf out/EaglerForge*
echo "Removed ."

git add . > /dev/null

echo "Commiting to repo..."
git commit -m "setupbuild commit" || echo "Nothing to commit" > /dev/null
echo "Git commit finished."

echo "Pulling & rebasing git repo..."
git pull --rebase origin main > /dev/null
echo "Pulled."
echo "Pushing to repo..."
git push origin HEAD:main > /dev/null
echo "Pushed."